nodeLinker: pnp
checksumBehavior: update

packageExtensions:
  eslint-config-next@*:
    dependencies:
      next: "*"
  eslint-plugin-tailwindcss@*:
    dependencies:
      tailwindcss: "^3"
  "@vitest/browser@*":
    peerDependencies:
      vite: "^6"
