import "./globals.css"

import { GoogleTagManager } from "@next/third-parties/google"
import { type Metadata } from "next"
import localFont from "next/font/local"
import { ThemeProvider } from "next-themes"

import { MSWComponent } from "../mocks/mswComponent"
import { OverlayProviderWrapper } from "./overlayProvider"
import { Providers } from "./providers"

export const metadata: Metadata = {
  title: "Re-Creation",
  description: "Generated by create next app",
}

const pretendard = localFont({
  src: "../../public/PretendardVariable.woff2",
  weight: "400",
  variable: "--font-pretendard",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className={pretendard.variable} suppressHydrationWarning>
      <GoogleTagManager gtmId="GTM-MGCJ2489" />
      <body>
        <MSWComponent>
          <Providers>
            <OverlayProviderWrapper>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
              >
                {children}
              </ThemeProvider>
            </OverlayProviderWrapper>
          </Providers>
        </MSWComponent>
      </body>
    </html>
  )
}
