name: Dev
# dev브랜치에 푸시되면 자동으로 실행되는 워크플로우
# 현재는 캐시 관련 작업을하기위해서만 사용중. 추후 배포관련 작업 시 다음 job부터 기입하면 됨
on:
  push:
    branches: [dev]

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
            .yarn/install-state.gz
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Get playwright version
        shell: bash
        run: |
          echo "PLAYWRIGHT_VERSION=$(yarn info playwright --json | jq -r '.children.Version')" >> $GITHUB_OUTPUT
        id: playwright-version

      - name: Cache Playwright Browsers for Playwright's Version
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}
          restore-keys: |
            ${{ runner.os }}-playwright-
        id: cache-playwright-browsers

      - name: Setup Playwright
        shell: bash
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: yarn exec playwright install --with-deps
